[package]
name = "bitcoin-consensus"
version = "0.14.1"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
build = "build.rs"

[dependencies]
bitflags = "*"
rustc-serialize = "*"
clippy = {version = "*", optional = true}

[build-dependencies]
num_cpus = "*"

[features]
default = []
